

import mongoose from 'mongoose'
import Product from '@/models/Product.model'
import doenv from 'dotenv'

doenv.config({ path: '.env.local' })


const products = [
    {
        name: "Apple iPad Air M2",
        slug: "apple-ipad-air-m2",
        description: "Powerful and portable tablet with M2 chip and Liquid Retina display.",
        price: 59900,
        comparePrice: 69900,
        images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600"],
        category: "electronics",
        brand: "apple",
        stock: 35,
        ratings: { average: 4.7, count: 142 },
        isFeatured: true,
        tags: ["tablet", "apple", "ipad", "new-arrivals"],
        specifications: { RAM: "8GB", Storage: "256GB", Display: "11 inch" },
    },
    {
        name: "Apple Watch Series 9",
        slug: "apple-watch-series-9",
        description: "Smartwatch with S9 chip, brighter display, and advanced health tracking.",
        price: 41900,
        comparePrice: 45900,
        images: ["https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600"],
        category: "electronics",
        brand: "apple",
        stock: 60,
        ratings: { average: 4.6, count: 203 },
        isFeatured: true,
        tags: ["smartwatch", "apple", "wearable", "best-seller"],
        specifications: { Case: "45mm", Connectivity: "GPS", Battery: "18 hours" },
    },
    {
        name: "AirPods Pro 2nd Gen",
        slug: "airpods-pro-2",
        description: "Wireless earbuds with active noise cancellation and adaptive audio.",
        price: 24900,
        comparePrice: 26900,
        images: ["https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600"],
        category: "electronics",
        brand: "apple",
        stock: 80,
        ratings: { average: 4.8, count: 389 },
        isFeatured: true,
        tags: ["earbuds", "apple", "audio", "best-seller"],
        specifications: { Battery: "30 hours", Connectivity: "Bluetooth 5.3", ANC: "Yes" },
    },
    {
        name: "Samsung Galaxy Tab S9",
        slug: "samsung-galaxy-tab-s9",
        description: "Premium Android tablet with AMOLED display and S Pen included.",
        price: 72999,
        comparePrice: 79999,
        images: ["https://images.unsplash.com/photo-1561154464-82e9adf32764?w=600"],
        category: "electronics",
        brand: "samsung",
        stock: 22,
        ratings: { average: 4.5, count: 76 },
        isFeatured: false,
        tags: ["tablet", "samsung", "android", "new-arrivals"],
        specifications: { RAM: "8GB", Storage: "128GB", Display: "11 inch" },
    },
    {
        name: "Samsung Galaxy Buds2 Pro",
        slug: "samsung-galaxy-buds2-pro",
        description: "Compact wireless earbuds with intelligent ANC and 360 audio.",
        price: 17999,
        comparePrice: 21999,
        images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600"],
        category: "electronics",
        brand: "samsung",
        stock: 65,
        ratings: { average: 4.4, count: 154 },
        isFeatured: false,
        tags: ["earbuds", "samsung", "audio", "summer-sale"],
        specifications: { Battery: "29 hours", Connectivity: "Bluetooth 5.3", ANC: "Yes" },
    },
    {
        name: "Sony PlayStation 5 Slim",
        slug: "sony-ps5-slim",
        description: "Next-gen gaming console with ultra-high speed SSD and 4K gaming.",
        price: 54990,
        comparePrice: 59990,
        images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600"],
        category: "electronics",
        brand: "sony",
        stock: 14,
        ratings: { average: 4.9, count: 267 },
        isFeatured: true,
        tags: ["gaming", "sony", "console", "best-seller"],
        specifications: { Storage: "1TB", Resolution: "4K", Type: "Disc Edition" },
    },
    {
        name: "Sony Alpha A7 IV Camera",
        slug: "sony-alpha-a7-iv",
        description: "Full-frame mirrorless camera with 33MP sensor and 4K video.",
        price: 244990,
        comparePrice: 269990,
        images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600"],
        category: "electronics",
        brand: "sony",
        stock: 8,
        ratings: { average: 4.8, count: 54 },
        isFeatured: false,
        tags: ["camera", "sony", "photography", "new-arrivals"],
        specifications: { Sensor: "33MP", Video: "4K 60fps", Mount: "E-mount" },
    },
    {
        name: "Dell Inspiron 14 Laptop",
        slug: "dell-inspiron-14",
        description: "Reliable everyday laptop with Intel Core i5 and slim design.",
        price: 64990,
        comparePrice: 74990,
        images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600"],
        category: "electronics",
        brand: "dell",
        stock: 28,
        ratings: { average: 4.2, count: 91 },
        isFeatured: false,
        tags: ["laptop", "dell", "windows", "summer-sale"],
        specifications: { RAM: "8GB", Storage: "512GB", Display: "14 inch" },
    },
    {
        name: "HP Pavilion Gaming Laptop",
        slug: "hp-pavilion-gaming",
        description: "Gaming laptop with RTX graphics and high refresh rate display.",
        price: 84990,
        comparePrice: 94990,
        images: ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600"],
        category: "electronics",
        brand: "hp",
        stock: 19,
        ratings: { average: 4.3, count: 73 },
        isFeatured: false,
        tags: ["laptop", "hp", "gaming", "best-seller"],
        specifications: { RAM: "16GB", Storage: "1TB", GPU: "RTX 4050" },
    },
    {
        name: "Lenovo ThinkPad X1 Carbon",
        slug: "lenovo-thinkpad-x1-carbon",
        description: "Business ultrabook with legendary keyboard and military-grade durability.",
        price: 149990,
        comparePrice: 169990,
        images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600"],
        category: "electronics",
        brand: "lenovo",
        stock: 11,
        ratings: { average: 4.6, count: 48 },
        isFeatured: true,
        tags: ["laptop", "lenovo", "business", "new-arrivals"],
        specifications: { RAM: "16GB", Storage: "1TB", Display: "14 inch" },
    },
    {
        name: "Asus ROG Strix Monitor",
        slug: "asus-rog-strix-monitor",
        description: "27-inch QHD gaming monitor with 165Hz refresh rate and G-Sync.",
        price: 32990,
        comparePrice: 38990,
        images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600"],
        category: "electronics",
        brand: "asus",
        stock: 24,
        ratings: { average: 4.5, count: 112 },
        isFeatured: false,
        tags: ["monitor", "asus", "gaming", "summer-sale"],
        specifications: { Size: "27 inch", Refresh: "165Hz", Resolution: "QHD" },
    },
    {
        name: "Logitech MX Master 3S Mouse",
        slug: "logitech-mx-master-3s",
        description: "Advanced wireless mouse with quiet clicks and precision scrolling.",
        price: 8995,
        comparePrice: 10995,
        images: ["https://images.unsplash.com/photo-1527814050087-3793815479db?w=600"],
        category: "electronics",
        brand: "logitech",
        stock: 90,
        ratings: { average: 4.7, count: 298 },
        isFeatured: false,
        tags: ["mouse", "logitech", "accessories", "best-seller"],
        specifications: { Connectivity: "Bluetooth", Battery: "70 days", DPI: "8000" },
    },
    {
        name: "Logitech MX Keys Keyboard",
        slug: "logitech-mx-keys",
        description: "Wireless illuminated keyboard with comfortable typing experience.",
        price: 10995,
        comparePrice: 12995,
        images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600"],
        category: "electronics",
        brand: "logitech",
        stock: 70,
        ratings: { average: 4.6, count: 176 },
        isFeatured: false,
        tags: ["keyboard", "logitech", "accessories", "summer-sale"],
        specifications: { Connectivity: "Bluetooth", Backlight: "Yes", Battery: "10 days" },
    },
    {
        name: "JBL Flip 6 Speaker",
        slug: "jbl-flip-6",
        description: "Portable waterproof Bluetooth speaker with bold sound.",
        price: 8999,
        comparePrice: 11999,
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600"],
        category: "electronics",
        brand: "jbl",
        stock: 85,
        ratings: { average: 4.5, count: 245 },
        isFeatured: false,
        tags: ["speaker", "jbl", "audio", "summer-sale"],
        specifications: { Battery: "12 hours", Waterproof: "IP67", Connectivity: "Bluetooth 5.1" },
    },
    {
        name: "Bose QuietComfort Ultra",
        slug: "bose-quietcomfort-ultra",
        description: "Premium noise cancelling headphones with immersive spatial audio.",
        price: 35900,
        comparePrice: 39900,
        images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600"],
        category: "electronics",
        brand: "bose",
        stock: 27,
        ratings: { average: 4.7, count: 134 },
        isFeatured: true,
        tags: ["headphones", "bose", "audio", "new-arrivals"],
        specifications: { Battery: "24 hours", ANC: "Yes", Connectivity: "Bluetooth 5.3" },
    },
    {
        name: "Nike Air Force 1",
        slug: "nike-air-force-1",
        description: "Timeless classic sneakers with clean leather upper.",
        price: 8295,
        comparePrice: 9995,
        images: ["https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600"],
        category: "footwear",
        brand: "nike",
        stock: 120,
        ratings: { average: 4.6, count: 512 },
        isFeatured: true,
        tags: ["shoes", "nike", "sneakers", "best-seller"],
        specifications: { Material: "Leather", Type: "Casual", Gender: "Unisex" },
    },
    {
        name: "Nike Pegasus 40",
        slug: "nike-pegasus-40",
        description: "Responsive everyday running shoes with React foam cushioning.",
        price: 11295,
        comparePrice: 13995,
        images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600"],
        category: "footwear",
        brand: "nike",
        stock: 65,
        ratings: { average: 4.5, count: 178 },
        isFeatured: false,
        tags: ["shoes", "nike", "running", "summer-sale"],
        specifications: { Material: "Mesh", Type: "Running", Gender: "Unisex" },
    },
    {
        name: "Adidas Samba OG",
        slug: "adidas-samba-og",
        description: "Iconic retro sneakers with suede overlays and gum sole.",
        price: 9999,
        comparePrice: 11999,
        images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600"],
        category: "footwear",
        brand: "adidas",
        stock: 88,
        ratings: { average: 4.7, count: 367 },
        isFeatured: true,
        tags: ["shoes", "adidas", "sneakers", "best-seller"],
        specifications: { Material: "Leather", Type: "Casual", Gender: "Unisex" },
    },
    {
        name: "Adidas Stan Smith",
        slug: "adidas-stan-smith",
        description: "Minimalist tennis-inspired sneakers with clean white finish.",
        price: 7999,
        comparePrice: 9999,
        images: ["https://images.unsplash.com/photo-1620794341491-7b9c3b8c0d1f?w=600"],
        category: "footwear",
        brand: "adidas",
        stock: 95,
        ratings: { average: 4.4, count: 289 },
        isFeatured: false,
        tags: ["shoes", "adidas", "sneakers", "summer-sale"],
        specifications: { Material: "Leather", Type: "Casual", Gender: "Unisex" },
    },
    {
        name: "Puma RS-X Sneakers",
        slug: "puma-rs-x",
        description: "Chunky retro-futuristic sneakers with bold colorways.",
        price: 8999,
        comparePrice: 10999,
        images: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600"],
        category: "footwear",
        brand: "puma",
        stock: 55,
        ratings: { average: 4.3, count: 143 },
        isFeatured: false,
        tags: ["shoes", "puma", "sneakers", "summer-sale"],
        specifications: { Material: "Mesh", Type: "Casual", Gender: "Unisex" },
    },
    {
        name: "New Balance 550",
        slug: "new-balance-550",
        description: "Retro basketball sneakers with vintage court styling.",
        price: 12999,
        comparePrice: 14999,
        images: ["https://images.unsplash.com/photo-1539185441755-769473a23570?w=600"],
        category: "footwear",
        brand: "new-balance",
        stock: 42,
        ratings: { average: 4.6, count: 156 },
        isFeatured: false,
        tags: ["shoes", "new-balance", "sneakers", "new-arrivals"],
        specifications: { Material: "Leather", Type: "Casual", Gender: "Unisex" },
    },
    {
        name: "Crocs Classic Clog",
        slug: "crocs-classic-clog",
        description: "Lightweight comfortable clogs with iconic ventilation ports.",
        price: 3995,
        comparePrice: 4995,
        images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600"],
        category: "footwear",
        brand: "crocs",
        stock: 150,
        ratings: { average: 4.5, count: 423 },
        isFeatured: false,
        tags: ["shoes", "crocs", "casual", "summer-sale"],
        specifications: { Material: "Croslite", Type: "Clog", Gender: "Unisex" },
    },
    {
        name: "Levis Trucker Jacket",
        slug: "levis-trucker-jacket",
        description: "Classic denim jacket with timeless rugged styling.",
        price: 5999,
        comparePrice: 7999,
        images: ["https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600"],
        category: "clothing",
        brand: "levis",
        stock: 70,
        ratings: { average: 4.4, count: 198 },
        isFeatured: false,
        tags: ["jacket", "levis", "denim", "new-arrivals"],
        specifications: { Material: "Denim", Fit: "Regular", Gender: "Unisex" },
    },
    {
        name: "Nike Dri-FIT T-Shirt",
        slug: "nike-dri-fit-tshirt",
        description: "Breathable athletic t-shirt with sweat-wicking technology.",
        price: 1995,
        comparePrice: 2495,
        images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600"],
        category: "clothing",
        brand: "nike",
        stock: 200,
        ratings: { average: 4.5, count: 334 },
        isFeatured: false,
        tags: ["tshirt", "nike", "activewear", "summer-sale"],
        specifications: { Material: "Polyester", Fit: "Regular", Gender: "Unisex" },
    },
    {
        name: "Adidas Track Pants",
        slug: "adidas-track-pants",
        description: "Comfortable tapered track pants with signature 3-stripes.",
        price: 3499,
        comparePrice: 4499,
        images: ["https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600"],
        category: "clothing",
        brand: "adidas",
        stock: 110,
        ratings: { average: 4.3, count: 167 },
        isFeatured: false,
        tags: ["pants", "adidas", "activewear", "summer-sale"],
        specifications: { Material: "Cotton Blend", Fit: "Tapered", Gender: "Unisex" },
    },
    {
        name: "H&M Cotton Hoodie",
        slug: "hm-cotton-hoodie",
        description: "Soft everyday hoodie with relaxed fit and kangaroo pocket.",
        price: 2499,
        comparePrice: 3499,
        images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600"],
        category: "clothing",
        brand: "hm",
        stock: 140,
        ratings: { average: 4.2, count: 256 },
        isFeatured: false,
        tags: ["hoodie", "hm", "casual", "summer-sale"],
        specifications: { Material: "Cotton", Fit: "Relaxed", Gender: "Unisex" },
    },
    {
        name: "Zara Slim Fit Shirt",
        slug: "zara-slim-fit-shirt",
        description: "Smart formal shirt with slim cut for a sharp look.",
        price: 2999,
        comparePrice: 3999,
        images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600"],
        category: "clothing",
        brand: "zara",
        stock: 85,
        ratings: { average: 4.3, count: 143 },
        isFeatured: false,
        tags: ["shirt", "zara", "formal", "new-arrivals"],
        specifications: { Material: "Cotton", Fit: "Slim", Gender: "Men" },
    },
    {
        name: "Uniqlo Ultra Light Down Jacket",
        slug: "uniqlo-ultra-light-down",
        description: "Packable lightweight down jacket for cold weather warmth.",
        price: 5990,
        comparePrice: 6990,
        images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600"],
        category: "clothing",
        brand: "uniqlo",
        stock: 60,
        ratings: { average: 4.6, count: 211 },
        isFeatured: true,
        tags: ["jacket", "uniqlo", "winter", "new-arrivals"],
        specifications: { Material: "Down", Fit: "Regular", Gender: "Unisex" },
    },
    {
        name: "Ray-Ban Aviator Sunglasses",
        slug: "rayban-aviator",
        description: "Iconic aviator sunglasses with polarized lenses and metal frame.",
        price: 8990,
        comparePrice: 10990,
        images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600"],
        category: "accessories",
        brand: "rayban",
        stock: 75,
        ratings: { average: 4.7, count: 298 },
        isFeatured: true,
        tags: ["sunglasses", "rayban", "accessories", "best-seller"],
        specifications: { Lens: "Polarized", Frame: "Metal", Gender: "Unisex" },
    },
    {
        name: "Fossil Gen 6 Smartwatch",
        slug: "fossil-gen-6",
        description: "Stylish hybrid smartwatch with health tracking and Wear OS.",
        price: 18995,
        comparePrice: 23995,
        images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600"],
        category: "accessories",
        brand: "fossil",
        stock: 40,
        ratings: { average: 4.2, count: 87 },
        isFeatured: false,
        tags: ["smartwatch", "fossil", "wearable", "summer-sale"],
        specifications: { OS: "Wear OS", Battery: "24 hours", Display: "AMOLED" },
    },
    {
        name: "Herschel Backpack",
        slug: "herschel-backpack",
        description: "Classic everyday backpack with padded laptop sleeve.",
        price: 6499,
        comparePrice: 7999,
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600"],
        category: "accessories",
        brand: "herschel",
        stock: 90,
        ratings: { average: 4.5, count: 234 },
        isFeatured: false,
        tags: ["backpack", "herschel", "accessories", "summer-sale"],
        specifications: { Capacity: "25L", Material: "Polyester", Laptop: "15 inch" },
    },
    {
        name: "Fastrack Analog Watch",
        slug: "fastrack-analog-watch",
        description: "Trendy analog watch with durable strap and minimalist dial.",
        price: 2495,
        comparePrice: 3495,
        images: ["https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600"],
        category: "accessories",
        brand: "fastrack",
        stock: 130,
        ratings: { average: 4.1, count: 312 },
        isFeatured: false,
        tags: ["watch", "fastrack", "accessories", "summer-sale"],
        specifications: { Type: "Analog", Strap: "Leather", Gender: "Unisex" },
    },
    {
        name: "American Tourister Trolley Bag",
        slug: "american-tourister-trolley",
        description: "Durable hard-shell trolley with smooth spinner wheels.",
        price: 7999,
        comparePrice: 11999,
        images: ["https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=600"],
        category: "accessories",
        brand: "american-tourister",
        stock: 50,
        ratings: { average: 4.4, count: 145 },
        isFeatured: false,
        tags: ["luggage", "travel", "accessories", "summer-sale"],
        specifications: { Size: "Medium", Material: "Polycarbonate", Wheels: "4" },
    },
    {
        name: "Dyson V12 Vacuum Cleaner",
        slug: "dyson-v12-vacuum",
        description: "Powerful cordless vacuum with laser dust detection.",
        price: 54900,
        comparePrice: 62900,
        images: ["https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600"],
        category: "home",
        brand: "dyson",
        stock: 18,
        ratings: { average: 4.7, count: 98 },
        isFeatured: true,
        tags: ["vacuum", "dyson", "home", "new-arrivals"],
        specifications: { Battery: "60 min", Type: "Cordless", Bin: "0.35L" },
    },
    {
        name: "Philips Air Fryer XL",
        slug: "philips-air-fryer-xl",
        description: "Large capacity air fryer for healthier fried food with less oil.",
        price: 12995,
        comparePrice: 16995,
        images: ["https://images.unsplash.com/photo-1626074353765-517a681e40be?w=600"],
        category: "home",
        brand: "philips",
        stock: 45,
        ratings: { average: 4.6, count: 287 },
        isFeatured: true,
        tags: ["kitchen", "philips", "home", "best-seller"],
        specifications: { Capacity: "6.2L", Power: "2000W", Type: "Air Fryer" },
    },
    {
        name: "Instant Pot Duo 7-in-1",
        slug: "instant-pot-duo",
        description: "Multi-functional electric pressure cooker for fast meals.",
        price: 8999,
        comparePrice: 11999,
        images: ["https://images.unsplash.com/photo-1585515320310-259814833e62?w=600"],
        category: "home",
        brand: "instant-pot",
        stock: 60,
        ratings: { average: 4.5, count: 421 },
        isFeatured: false,
        tags: ["kitchen", "cooker", "home", "summer-sale"],
        specifications: { Capacity: "6L", Functions: "7", Power: "1000W" },
    },
    {
        name: "Mi Smart LED TV 55 inch",
        slug: "mi-smart-led-tv-55",
        description: "4K Ultra HD smart TV with Dolby Vision and Android TV.",
        price: 38999,
        comparePrice: 49999,
        images: ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600"],
        category: "electronics",
        brand: "mi",
        stock: 30,
        ratings: { average: 4.3, count: 176 },
        isFeatured: false,
        tags: ["tv", "mi", "home", "best-seller"],
        specifications: { Size: "55 inch", Resolution: "4K", OS: "Android TV" },
    },
    {
        name: "Nespresso Vertuo Coffee Machine",
        slug: "nespresso-vertuo",
        description: "Premium coffee machine brewing espresso and coffee at one touch.",
        price: 15990,
        comparePrice: 18990,
        images: ["https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600"],
        category: "home",
        brand: "nespresso",
        stock: 25,
        ratings: { average: 4.6, count: 134 },
        isFeatured: false,
        tags: ["coffee", "kitchen", "home", "new-arrivals"],
        specifications: { Type: "Capsule", Capacity: "1.1L", Power: "1350W" },
    },
    {
        name: "Maybelline Fit Me Foundation",
        slug: "maybelline-fit-me-foundation",
        description: "Lightweight foundation with natural matte finish for all skin tones.",
        price: 549,
        comparePrice: 699,
        images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600"],
        category: "beauty",
        brand: "maybelline",
        stock: 250,
        ratings: { average: 4.4, count: 567 },
        isFeatured: false,
        tags: ["makeup", "maybelline", "beauty", "best-seller"],
        specifications: { Type: "Foundation", Finish: "Matte", Volume: "30ml" },
    },
    {
        name: "The Ordinary Niacinamide Serum",
        slug: "the-ordinary-niacinamide",
        description: "Concentrated serum to reduce blemishes and balance oil.",
        price: 590,
        comparePrice: 750,
        images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600"],
        category: "beauty",
        brand: "the-ordinary",
        stock: 180,
        ratings: { average: 4.5, count: 389 },
        isFeatured: true,
        tags: ["skincare", "serum", "beauty", "new-arrivals"],
        specifications: { Type: "Serum", Volume: "30ml", Concern: "Blemishes" },
    },
    {
        name: "Cetaphil Gentle Cleanser",
        slug: "cetaphil-gentle-cleanser",
        description: "Mild face wash suitable for sensitive and dry skin.",
        price: 899,
        comparePrice: 1099,
        images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600"],
        category: "beauty",
        brand: "cetaphil",
        stock: 200,
        ratings: { average: 4.6, count: 445 },
        isFeatured: false,
        tags: ["skincare", "cleanser", "beauty", "summer-sale"],
        specifications: { Type: "Cleanser", Volume: "250ml", Skin: "Sensitive" },
    },
    {
        name: "Wild Stone Perfume",
        slug: "wild-stone-perfume",
        description: "Long-lasting woody fragrance for everyday wear.",
        price: 449,
        comparePrice: 599,
        images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=600"],
        category: "beauty",
        brand: "wild-stone",
        stock: 160,
        ratings: { average: 4.2, count: 234 },
        isFeatured: false,
        tags: ["fragrance", "perfume", "beauty", "summer-sale"],
        specifications: { Type: "Perfume", Volume: "100ml", Notes: "Woody" },
    },
    {
        name: "Yonex Badminton Racket",
        slug: "yonex-badminton-racket",
        description: "Lightweight graphite racket for powerful and controlled play.",
        price: 4999,
        comparePrice: 6999,
        images: ["https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600"],
        category: "sports",
        brand: "yonex",
        stock: 70,
        ratings: { average: 4.5, count: 198 },
        isFeatured: false,
        tags: ["badminton", "yonex", "sports", "summer-sale"],
        specifications: { Material: "Graphite", Weight: "85g", Type: "Racket" },
    },
    {
        name: "Cosco Football Size 5",
        slug: "cosco-football-size-5",
        description: "Durable match football with good grip and bounce.",
        price: 899,
        comparePrice: 1299,
        images: ["https://images.unsplash.com/photo-1614632537190-23e4146777db?w=600"],
        category: "sports",
        brand: "cosco",
        stock: 120,
        ratings: { average: 4.3, count: 167 },
        isFeatured: false,
        tags: ["football", "cosco", "sports", "summer-sale"],
        specifications: { Size: "5", Material: "Rubber", Type: "Match" },
    },
    {
        name: "Boldfit Yoga Mat",
        slug: "boldfit-yoga-mat",
        description: "Anti-slip cushioned yoga mat for comfortable workouts.",
        price: 799,
        comparePrice: 1499,
        images: ["https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=600"],
        category: "sports",
        brand: "boldfit",
        stock: 200,
        ratings: { average: 4.4, count: 512 },
        isFeatured: false,
        tags: ["yoga", "fitness", "sports", "best-seller"],
        specifications: { Thickness: "6mm", Material: "TPE", Length: "183cm" },
    },
    {
        name: "PowerMax Adjustable Dumbbells",
        slug: "powermax-dumbbells",
        description: "Space-saving adjustable dumbbell set for home gym.",
        price: 7999,
        comparePrice: 11999,
        images: ["https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=600"],
        category: "sports",
        brand: "powermax",
        stock: 35,
        ratings: { average: 4.5, count: 143 },
        isFeatured: true,
        tags: ["fitness", "gym", "sports", "new-arrivals"],
        specifications: { Weight: "20kg", Type: "Adjustable", Set: "Pair" },
    },
    {
        name: "Atomic Habits Book",
        slug: "atomic-habits-book",
        description: "Bestselling guide to building good habits and breaking bad ones.",
        price: 399,
        comparePrice: 699,
        images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600"],
        category: "books",
        brand: "penguin",
        stock: 300,
        ratings: { average: 4.8, count: 1024 },
        isFeatured: true,
        tags: ["book", "self-help", "books", "best-seller"],
        specifications: { Author: "James Clear", Pages: "320", Language: "English" },
    },
    {
        name: "Kindle Paperwhite",
        slug: "kindle-paperwhite",
        description: "Waterproof e-reader with glare-free display and weeks of battery.",
        price: 13999,
        comparePrice: 16999,
        images: ["https://images.unsplash.com/photo-1592434134753-a70baf7979d5?w=600"],
        category: "electronics",
        brand: "amazon",
        stock: 55,
        ratings: { average: 4.7, count: 389 },
        isFeatured: true,
        tags: ["ereader", "kindle", "books", "best-seller"],
        specifications: { Storage: "16GB", Display: "6.8 inch", Waterproof: "IPX8" },
    },
    {
        name: "Anker PowerCore 20000",
        slug: "anker-powercore-20000",
        description: "High-capacity portable power bank with fast charging.",
        price: 3499,
        comparePrice: 4999,
        images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600"],
        category: "electronics",
        brand: "anker",
        stock: 110,
        ratings: { average: 4.6, count: 456 },
        isFeatured: false,
        tags: ["powerbank", "anker", "accessories", "summer-sale"],
        specifications: { Capacity: "20000mAh", Ports: "2", Output: "20W" },
    },
];



async function seed() {
    try {
        await mongoose.connect(process.env.MONGO_URI!)
        console.log("Mongodb connected")

        await Product.deleteMany()
        console.log("Deleted all products")

        await Product.insertMany(products)
        console.log("Inserted all products")

        mongoose.connection.close()

        console.log("Seeding completed successfully")
        process.exit(0)
    } catch (err) {
        console.log(err)
    }
}

seed()