import type { Metadata } from "next";
import "../globals.css";
import { cookies } from "next/headers";
import { verifyToken } from "@/lib/auth";
import { redirect } from "next/navigation";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: {
    template: "%s | ShopMart",
    default: "ShopMart - Premium E-commerce Template",
  },
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={null}>
      <RequireAdminUser>{children}</RequireAdminUser>
    </Suspense>
  );
}

async function RequireAdminUser({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies()
  const token = cookieStore.get(process.env.JWT_COOKIE_NAME!)?.value;
  const decode = token ? verifyToken(token) : null;

  if (!decode) {
    redirect('/login')
  }

  if (decode.role !== 'admin' && decode.role !== 'superadmin') {
    redirect('/')
  }

  return children
}